[package]
name = "nyado"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
users = "0.11.0"
libc = "0.2.162"
pam = { version = "0.7.0", optional = true }

[features]
default = ["pam"]
pam = ["dep:pam"]

